@include('MainLayouts/header')
@include('MainLayouts/mainheader')
    @include('MainLayouts/leftsidebar')
    @include('Admin/layouts/Properties/sub_viewCreateProperty') 
@include('MainLayouts/footer')