@include('MainLayouts/header')
@include('MainLayouts/mainheader')
  @include('MainLayouts/leftsidebar')
    @include('Admin/layouts/Categories/sub_viewCreateCategory') 
@include('MainLayouts/footer')
