
//home page
export const HOME_PAGE_REQUEST = 'ALL_PAGE_REQUEST'

export const HOME_PAGE_SUCCESS = 'ALL_PAGE_SUCCESS'

export const HOME_PAGE_FAIL = 'ALL_PAGE_FAIL'

// product details page
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'

export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'

export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

// search page
export const SEARCH_PAGE_REQUEST = 'SEARCH_PAGE_REQUEST'

export const SEARCH_PAGE_SUCCESS = 'SEARCH_PAGE_SUCCESS'

export const SEARCH_PAGE_FAIL = 'SEARCH_PAGE_FAIL'

// brand categories page
export const BRAND_CATEGORIES_PAGE_REQUEST = 'BRAND_CATEGORIES_PAGE_REQUEST'

export const BRAND_CATEGORIES_PAGE_SUCCESS = 'BRAND_CATEGORIES_PAGE_SUCCESS'

export const BRAND_CATEGORIES_PAGE_FAIL = 'BRAND_CATEGORIES_PAGE_FAIL'

// sub categories page
export const SUB_CATEGORIES_PAGE_REQUEST = 'SUB_CATEGORIES_PAGE_REQUEST'

export const SUB_CATEGORIES_PAGE_SUCCESS = 'SUB_CATEGORIES_PAGE_SUCCESS'

export const SUB_CATEGORIES_PAGE_FAIL = 'SUB_CATEGORIES_PAGE_FAIL'

//categories items page
export const CATEGORY_ITEMS_PAGE_REQUEST = 'CATEGORY_ITEMS_PAGE_REQUEST'

export const CATEGORY_ITEMS_PAGE_SUCCESS = 'CATEGORY_ITEMS_PAGE_SUCCESS'

export const CATEGORY_ITEMS_PAGE_FAIL = 'CATEGORY_ITEMS_PAGE_FAIL'

// favorite items 
export const FAVORITE_ITEMS_REQUEST = 'FAVORITE_ITEMS_REQUEST'

export const FAVORITE_ITEMS_SUCCESS = 'FAVORITE_ITEMS_SUCCESS'

export const FAVORITE_ITEMS_FAIL = 'FAVORITE_ITEMS_FAIL'

// cart items 
export const ORDER_REQUEST = 'ORDER_REQUEST'

export const ORDER_SUCCESS = 'ORDER_SUCCESS'

export const ORDER_FAIL = 'ORDER_FAIL'

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGIN_FAIL = 'LOGIN_FAIL'

// register
export const REGISTER_REQUEST = 'REGISTER_REQUEST'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const REGISTER_FAIL = 'REGISTER_FAIL'

// get Profile user
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'

export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'

export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

// logout
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const LOGOUT_FAIL = 'LOGOUT_FAIL'

// get social sign up
export const SOCIAL_SIGNUP_REQUEST = 'SOCIAL_SIGNUP_REQUEST'

export const SOCIAL_SIGNUP_SUCCESS = 'SOCIAL_SIGNUP_SUCCESS'

export const SOCIAL_SIGNUP_FAIL = 'SOCIAL_SIGNUP_FAIL'

// update profile
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'

export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

// get address
export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST'

export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'

export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'

